### ISSUE TITLE
Simulation of coin toss game question

### ISSUE THREAD

**Issue by moritz-stephan** [LMLhub/ee_lecture_notes#11]
Hi, I simulated the coin tossing game myself and I'm a bit confused by the result. When I keep t relatively low (<200) I get the expected growth rate of the sample (n=100000) of 1.05, but when I increase t to lets say 1000, the sample wealth diverges from the mathematically expected. Does this mean the ensemble only grows at that rate in the short-run? Below is my code for reference.
![sample_avg](https://user-images.githubusercontent.com/58358975/69900309-d1c80400-1371-11ea-9fe1-1b5760cfc3e1.png)

```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

n=100000
t=1000
up=1.5
down = 0.6
p=0.5

sample = []
for i in range(n):
    trajectory = [1]
    for k in range(t):
        if np.random.random() > p:
            trajectory.append(trajectory[-1]*down)
        else:
            trajectory.append(trajectory[-1]*up)
    
    sample.append(trajectory)

plt.plot(np.mean(sample,axis=0))
x=np.linspace(0,t,t)
y=1.05**x
plt.plot(x,y)


sample_avg= pd.Series(np.mean(sample,axis=0)).pct_change().mean()

```

**Comment by FG-CTRI** [comment]
Moritz-Stephan: exploring similar issues in Excel, see link. 

[2019.CTRI.EEGamble.Extension.Discord.xlsx](https://github.com/LMLhub/ee_lecture_notes/files/3908496/2019.CTRI.EEGamble.Extension.Discord.xlsx)

**Comment by ole-peters** [comment]
Hi, yes, that's exactly what it means. Read on... you'll find a graph very similar to yours on p.96, section 6.2 Finite Populations.
