### ISSUE TITLE
Notation Matrix

### ISSUE THREAD

**Issue by FG-CTRI** [LMLhub/ee_lecture_notes#14]
Reading the book requires paying close attention to the notation conventions. See attached matrix that is part of the process of cataloging and comparing notation, starting with the calculations of single period and multiple period returns and rates of return. These matrices are my maps as well as translation tables as i read the material. Would they be helpful to other readers if they were included in the book? They may also help us hunt for lacunae, should there be any.
[CTRI.2019DEC3.EE.ppt.Matrix.Notation.Github.fg.pptx](https://github.com/LMLhub/ee_lecture_notes/files/3919278/CTRI.2019DEC3.EE.ppt.Matrix.Notation.Github.fg.pptx)

**Comment by unbalancedparentheses** [comment]
Great comment @FG-CTRI. I think @alex-adamou and @ole-peters are working on a list of symbols that is more extensive than the one you uploaded. Stay tuned!

**Comment by FG-CTRI** [comment]
Federico,

Thanks. Much appreciated.

Great work on RGBM by the way.

A few thoughts about the model and potential extensions:

1- Are you familiar with the book "Engines that Move Markets" by 
Alasdair Nairn?

https://www.amazon.com/Engines-That-Markets-Alisdair-Nairn/dp/0857195999/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1575494030&sr=8-1

He traces the waves of innovations since the industrial revolution. All 
show crazy growth and crazy crashes.

2- I wonder what happens when we model finite lifetimes (that may be 
shorter than the long-time limit runs), the impact of generational 
transitions (shirtsleeves to shirtsleeves in three generations), estate 
taxes, etc.

Cheers,

Francois

**Comment by unbalancedparentheses** [comment]
I am not familiar with the book. I will check it. Regarding 2 I don't know. I think Ole is better suited to answer that question.

I will close this since I know they are working on the symbol table
